[package]
name = "rustycdn"
version = "0.1.0"
authors = ["Alexander von Gluck IV <kallisti5@unixzen.com>"]

[dependencies]
iron = "0.6.0"
router = "0.6.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
getopts = "*"
